aggregation: mean
batch_size: 32
class_weights: true
data:
  dataset: WICO
  pre_filter: filter_5g_non
  pre_transform: wico_data_to_custom
  root: wico
dataset: wico
device: cuda
dropout: 0.5
epochs: 100
hidden_units:
- 32
- 32
- 32
- 32
improvement_threshold: 0.01
kfolds: 5
loss_fn: CrossEntropyLoss
lr: 0.01
model: GIN
optimizer: Adam
patience: 7
train_eps: true
transform: wico_5g_non_oversampled
