device: 'cpu'

# DATA
dataset: 'wico'
transform: 'torch_dummy_transform'
class_weights: True

# MODEL
model: 'TorchDummy'

# TRAINING
kfolds: 2
optimizer: Adam
loss_fn: CrossEntropyLoss
batch_size: 32
epochs: 1
lr: 0.01
# add: early stopping config options
