device: 'cuda'

# DATA
data: {
  dataset: 'WICO',
  root: 'wico',
  pre_filter: 'filter_5g_non',
  pre_transform: 'wico_data_to_custom'
  }

dataset: 'wico'
transform: 'wico_5g_vs_non_conspiracy'
class_weights: false

# MODEL
model: 'GIN'
hidden_units: [32, 32, 32]
train_eps: True
aggregation: sum
dropout: 0.0

# TRAINING
kfolds: 5
optimizer: Adam
loss_fn: CrossEntropyLoss
batch_size: 32
epochs: 50
lr: 0.01

# EARLY STOPPING
patience: 5
improvement_threshold: 0.05
