device: 'cpu'

# DATA
dataset: 'wico'
transform: 'wico_5g_vs_non_conspiracy'
class_weights: True

# MODEL
model: 'GIN'
hidden_units:
  - [32]
train_eps: 
- false
aggregation: 
- sum
- mean
dropout: 
  - 0.0

# TRAINING
kfolds: 2
optimizer: Adam
loss_fn: CrossEntropyLoss
batch_size:
  - 32
epochs: 2
lr:
  - 0.01
# TODO: add early stopping config options