device: 'cpu'

# DATA
dataset: 'wico'
transform: 'wico_5g_vs_non_conspiracy'
class_weights: True

# MODEL
model: 'GIN'
hidden_units:
  - [32]
  - [64]
train_eps: 
- true
- false
aggregation: 
- sum
dropout: 
  - 0.0

# TRAINING
kfolds: 5
optimizer: Adam
loss_fn: CrossEntropyLoss
batch_size:
  - 32
  - 64
epochs: 1
lr:
  - 0.01
  - 0.1

# EARLY STOPPING
patience: 5
improvement_threshold: 0.05