device: 'cpu'

# DATA
dataset: 'wico'
transform: 'wico_5g_vs_non_conspiracy'
class_weights: True

# MODEL
model: 'GIN'
hidden_units:
  - [32, 32, 32]
  
train_eps: 
- true
aggregation: 
- mean
dropout: 
  - 0.5

# TRAINING
kfolds: 
  - 5
  - 4
  - 3
  - 2
optimizer: Adam
loss_fn: CrossEntropyLoss
batch_size:
  - 128
epochs: 20
lr:
  - 0.01

# EARLY STOPPING
patience: 5
improvement_threshold: 0.01